# HRV、PLI、アンケート、kubios_HRVをつなげるプログラム

In [3]:
import sys
sys.path.append('..')
from Constants import Constants

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import glob
import re

In [4]:
pd.set_option('display.max_columns', 30)

In [5]:
HRV_pathes = glob.glob("/Users/miyakooti/repositories/arai_MATLAB_program/csv/?_*/ECG/*_HRV.csv")
HRV_pathes.sort()
HRV_pathes

['/Users/miyakooti/repositories/arai_MATLAB_program/csv/0_kumakura/ECG/kumakura_HRV.csv',
 '/Users/miyakooti/repositories/arai_MATLAB_program/csv/1_kim/ECG/kim_HRV.csv',
 '/Users/miyakooti/repositories/arai_MATLAB_program/csv/2_souma/ECG/souma_HRV.csv',
 '/Users/miyakooti/repositories/arai_MATLAB_program/csv/3_fujii/ECG/fujii_HRV.csv',
 '/Users/miyakooti/repositories/arai_MATLAB_program/csv/4_tubota/ECG/tubota_HRV.csv',
 '/Users/miyakooti/repositories/arai_MATLAB_program/csv/5_toki/ECG/toki_HRV.csv']

In [6]:
PLI_pathes = glob.glob("/Users/miyakooti/repositories/arai_MATLAB_program/csv/?_*/PLIdata/mean_PLI_*.csv")
PLI_pathes.sort()
PLI_pathes

['/Users/miyakooti/repositories/arai_MATLAB_program/csv/0_kumakura/PLIdata/mean_PLI_kumakura.csv',
 '/Users/miyakooti/repositories/arai_MATLAB_program/csv/1_kim/PLIdata/mean_PLI_kim.csv',
 '/Users/miyakooti/repositories/arai_MATLAB_program/csv/2_souma/PLIdata/mean_PLI_souma.csv',
 '/Users/miyakooti/repositories/arai_MATLAB_program/csv/3_fujii/PLIdata/mean_PLI_fujii.csv',
 '/Users/miyakooti/repositories/arai_MATLAB_program/csv/4_tubota/PLIdata/mean_PLI_tubota.csv',
 '/Users/miyakooti/repositories/arai_MATLAB_program/csv/5_toki/PLIdata/mean_PLI_toki.csv']

In [7]:
questionnarie_pathes = glob.glob("/Users/miyakooti/repositories/arai_MATLAB_program/csv/?_*/questionnarie.csv")
questionnarie_pathes.sort()
questionnarie_pathes

['/Users/miyakooti/repositories/arai_MATLAB_program/csv/0_kumakura/questionnarie.csv',
 '/Users/miyakooti/repositories/arai_MATLAB_program/csv/1_kim/questionnarie.csv',
 '/Users/miyakooti/repositories/arai_MATLAB_program/csv/2_souma/questionnarie.csv',
 '/Users/miyakooti/repositories/arai_MATLAB_program/csv/3_fujii/questionnarie.csv',
 '/Users/miyakooti/repositories/arai_MATLAB_program/csv/4_tubota/questionnarie.csv',
 '/Users/miyakooti/repositories/arai_MATLAB_program/csv/5_toki/questionnarie.csv']

In [8]:
kubios_pathes = glob.glob("/Users/miyakooti/repositories/arai_MATLAB_program/csv/?_*/kubios_HRV.csv")
kubios_pathes.sort()
kubios_pathes

['/Users/miyakooti/repositories/arai_MATLAB_program/csv/0_kumakura/kubios_HRV.csv',
 '/Users/miyakooti/repositories/arai_MATLAB_program/csv/1_kim/kubios_HRV.csv',
 '/Users/miyakooti/repositories/arai_MATLAB_program/csv/2_souma/kubios_HRV.csv',
 '/Users/miyakooti/repositories/arai_MATLAB_program/csv/3_fujii/kubios_HRV.csv',
 '/Users/miyakooti/repositories/arai_MATLAB_program/csv/4_tubota/kubios_HRV.csv',
 '/Users/miyakooti/repositories/arai_MATLAB_program/csv/5_toki/kubios_HRV.csv']

In [9]:
hrv_df = pd.read_csv(f"{HRV_pathes[0]}")
hrv_df

,Unnamed: 0,bpm,ibi,sdnn,sdsd,rmssd,pnn20,pnn50,hr_mad,sd1,sd2,s,sd1/sd2,breathingrate,vlf,lf,hf,lf/hf,p_total,vlf_perc,lf_perc,hf_perc,lf_nu,hf_nu,lf_diff,hf_diff,lfhf_diff
0,rest,74.087015,809.858521,41.250305,20.146486,36.787621,0.619355,0.183871,30.0,26.012686,52.268898,4271.480335,0.497670,0.300000,396.011131,338.306267,533.157937,0.634533,1267.475336,31.244090,26.691349,42.064561,38.820443,61.179557,0.000000,0.000000,0.000000
1,boredom,76.136223,788.061162,38.553302,16.680887,31.258471,0.582822,0.092025,22.0,22.103056,49.826426,3459.887136,0.443601,0.366667,518.685695,348.261920,297.243050,1.171640,1164.190666,44.553329,29.914509,25.532162,53.951857,46.048143,-9.955653,235.914887,-0.537107
2,flow,79.897427,750.962861,43.874994,16.548756,29.365935,0.541322,0.084022,30.0,20.764207,58.349347,3806.284253,0.355860,0.128217,971.981731,207.806086,79.141757,2.625745,1258.929574,77.206998,16.506570,6.286432,72.419463,27.580537,130.500182,454.016180,-1.991212
3,ultra,79.017461,759.325843,67.135244,20.173773,34.786191,0.581921,0.169492,58.0,24.591192,91.571813,7074.427022,0.268545,0.166667,1381.615908,275.811328,124.147392,2.221644,1781.574629,77.550269,15.481323,6.968408,68.959949,31.040051,62.494939,409.010545,-1.587111
4,overload,76.508025,784.231454,37.720271,19.232687,32.628136,0.529762,0.122024,26.0,23.071538,48.137820,3489.095291,0.479281,0.133333,521.107310,232.051713,215.334734,1.077633,968.493757,53.805954,23.960063,22.233983,51.868293,48.131707,106.254554,317.823203,-0.443100

In [10]:
pli_df = pd.read_csv(f"{PLI_pathes[0]}")
pli_df

,Unnamed: 0,FpZ,FC3,FC4,FCz,O1,O2,Fp2,mean_all,mean_3ch,concentration_FC3,concentration_FC4,concentration_FCz,concentration_mean
0,rest,0.47038,0.71824,0.53059,0.78305,0.35243,0.28658,0.39018,0.504493,0.677293,NaN,NaN,NaN,NaN
1,practice,0.27293,0.38358,0.47002,0.54056,0.34591,0.32768,0.19776,0.362634,0.464720,0.209593,0.060921,0.174494,0.148336
2,boredom,0.28649,0.43996,0.43761,0.54694,0.17318,0.15961,0.23876,0.326079,0.474837,0.272161,0.092863,0.222104,0.195709
3,flow,0.26200,0.42757,0.43541,0.37519,0.66146,0.52691,0.25446,0.420429,0.412723,0.290671,0.095183,0.407868,0.264574
4,ultra,0.65670,0.75545,0.80386,0.77300,0.86585,0.81846,0.60434,0.753951,0.777437,0.164482,-0.071325,0.238026,0.110395
5,overload,0.12267,0.28812,0.42067,0.50908,0.24092,0.20799,0.15147,0.277274,0.405957,0.426403,0.112814,0.271573,0.270263

In [11]:
questionnarie_df = pd.read_csv(f"{questionnarie_pathes[0]}")
questionnarie_df

  Unnamed: 0 difficulty  fast  fulfillment  absorb  questionnaire_average
0       rest        NaN   NaN          NaN     NaN                    NaN
1   practice   \t\t\t\t   NaN          NaN     NaN                    NaN
2    boredom          2   2.0          5.0     2.0                   2.75
3       flow          7   7.0          7.0     7.0                   7.00
4      ultra          5   7.0          6.0     7.0                   6.25
5   overload          7   6.0          2.0     6.0                   5.25

In [12]:
kubios_df = pd.read_csv(f"{questionnarie_pathes[0]}")
kubios_df

  Unnamed: 0 difficulty  fast  fulfillment  absorb  questionnaire_average
0       rest        NaN   NaN          NaN     NaN                    NaN
1   practice   \t\t\t\t   NaN          NaN     NaN                    NaN
2    boredom          2   2.0          5.0     2.0                   2.75
3       flow          7   7.0          7.0     7.0                   7.00
4      ultra          5   7.0          6.0     7.0                   6.25
5   overload          7   6.0          2.0     6.0                   5.25

In [14]:
for i in range(0, int(len(HRV_pathes))):

    pli_path = PLI_pathes[i]
    pli_df = pd.read_csv(f"{pli_path}",index_col=0)
    
    hrv_path = HRV_pathes[i]
    hrv_df = pd.read_csv(f"{hrv_path}",index_col=0)
    
    questionnarie_path = questionnarie_pathes[i]
    questionnarie_df = pd.read_csv(f"{questionnarie_path}",index_col=0)
    
    kubios_path = kubios_pathes[i]
    kubios_df = pd.read_csv(f"{kubios_path}",index_col=0)
    
    df_concatted = pd.concat([hrv_df,kubios_df], axis=1) # 横（axis=1）連結(concat) 
    df_concatted = pd.concat([df_concatted,pli_df], axis=1) # 横（axis=1）連結(concat)    
    df_concatted = pd.concat([df_concatted,questionnarie_df], axis=1) # 横（axis=1）連結(concat)    
    df_concatted.to_csv(f"/Users/miyakooti/repositories/arai_MATLAB_program/csv/{i}_{Constants.subject_name_list[i]}/HRV_and_PLI.csv")

# ↓ sandbox
esc, enterで青と緑の切り替え
青状態のときにMでマークダウン

# [pandas参考文献](https://qiita.com/ysdyt/items/9ccca82fc5b504e7913a)

In [15]:
hrv_df[["lf","hf","lf/hf"]]

                   lf          hf     lf/hf
rest      1231.720452  138.655648  8.883305
boredom    830.045789  211.114474  3.931733
flow       457.744936  155.995954  2.934339
ultra      157.002619   55.390693  2.834458
overload   415.759892  103.952783  3.999507

### 左のヘッダーはインデックスというらしい
https://note.nkmk.me/python-pandas-read-csv-tsv/

In [ ]:
hrv_df = pd.read_csv(f"{HRV_pathes[0]}", index_col=0)
hrv_df

In [ ]:
pli_df = pd.read_csv(f"{PLI_pathes[0]}", index_col=0)
pli_df

In [ ]:
df_concatted = pd.concat([hrv_df,pli_df], axis=1)
df_concatted

In [ ]:
# df_concatted.o_csv("/Users/miyakooti/repositories/arai_MATLAB_program/csv/0_kumakura/HRV_and_PLI.csv")

### [右結合とか左結合とかがわかるリンク](https://ai-inter1.com/pandas-dataframe_join/#st-toc-h-1)
- 連結はconcat
    - ただただガッちゃんこする
- 結合はmerge
    - 共通キーを指定して結合する